# Generated by Django on initial setup
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('direction', models.CharField(choices=[('DIRECTION_1', 'Direction 1'), ('DIRECTION_2', 'Direction 2'), ('BOTH', 'Both Directions')], max_length=20)),
                ('event_type', models.CharField(choices=[('LIGHT_CHANGE', 'Light Change'), ('VEHICLE_DETECTED', 'Vehicle Detected'), ('NO_VEHICLE', 'No Vehicle'), ('SYSTEM_START', 'System Start'), ('SYSTEM_STOP', 'System Stop'), ('ERROR', 'Error')], max_length=20)),
                ('description', models.TextField()),
                ('vehicles_detected', models.IntegerField(default=0)),
                ('light_state', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('direction_1_light', models.CharField(default='RED', max_length=10)),
                ('direction_2_light', models.CharField(default='RED', max_length=10)),
                ('direction_1_vehicles', models.IntegerField(default=0)),
                ('direction_2_vehicles', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Status',
            },
        ),
        migrations.AddIndex(
            model_name='trafficevent',
            index=models.Index(fields=['-timestamp'], name='traffic_con_timesta_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficevent',
            index=models.Index(fields=['direction', '-timestamp'], name='traffic_con_directi_idx'),
        ),
    ]
